version: '3'
services:
  ### postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### postgres database for Orders
  db-orders:
    container_name: db-orders
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    command: -p 3306

  ### postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

